### ISSUE TITLE
Image Not Loading On Google Chrome

### ISSUE THREAD

**Issue by dbigueta** [wiedesign/GarbageCollectorRobot#10]
## User Story
There is a bug with images being loaded on firefox but not on google chrome.

## Notes
The problem is because google chrome sets an inline style of "display: none !important". We have to find out how to prevent that from happening or overwritting that command. It will be difficult to overwrite since inline styles have the highest specificity and it's also using the !important command.

I believe it's something to do with the Google Chrome version that's being used.

## Acceptance Criteria
- [ ] The social media images loads on the google chrome web browser

**Comment by sarahraisuddin** [comment]
The images were being blocked because the outdated ad blocker extension I had installed on chrome registered the icons as ads.
